DROP TABLE IF EXISTS aPrGenre;
DROP TABLE IF EXISTS Genre;

CREATE TABLE IF NOT EXISTS Genre (
	idGenre SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	nomGenre VARCHAR(20) NOT NULL,
	PRIMARY KEY (idGenre)
)
ENGINE=INNODB;

LOAD DATA LOCAL INFILE '/home/coralie/luna/Film/Genre.csv'
INTO TABLE Genre
FIELDS TERMINATED BY ';' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(idGenre,nomGenre);

ALTER TABLE Genre
ADD UNIQUE indexGenre (nomGenre(10));

CREATE TABLE IF NOT EXISTS aPrGenre(
	idFilm SMALLINT UNSIGNED NOT NULL,
	idGenre SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (idFilm,idGenre),
	CONSTRAINT fk_idFilmGenre
        FOREIGN KEY (idFilm)
        REFERENCES Film(idFilm) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=INNODB;

ALTER TABLE aPrGenre
ADD CONSTRAINT fk_idGenre FOREIGN KEY (idGenre) REFERENCES Genre(idGenre) 
ON DELETE CASCADE
ON UPDATE CASCADE;

LOAD DATA LOCAL INFILE '/home/coralie/luna/Film/aPrGenre.csv'
INTO TABLE aPrGenre
FIELDS TERMINATED BY ';' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(idFilm,idGenre);
