DROP TABLE IF EXISTS aPrTag;
DROP TABLE IF EXISTS Tag;

CREATE TABLE IF NOT EXISTS Tag(
	idTag SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	nomTag VARCHAR(40) NOT NULL,
	PRIMARY KEY (idTag)
)
ENGINE=INNODB;

LOAD DATA LOCAL INFILE '/home/coralie/luna/Film/Tag.csv'
INTO TABLE Tag
FIELDS TERMINATED BY ';' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(idTag,nomTag);



CREATE TABLE IF NOT EXISTS aPrTag(
	idFilm SMALLINT UNSIGNED NOT NULL ,
	idTag SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (idFilm,idTag),
	CONSTRAINT fk_idFilmTag
        FOREIGN KEY (idFilm)
        REFERENCES Film(idFilm) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=INNODB;

ALTER TABLE aPrTag
ADD CONSTRAINT fk_idTag FOREIGN KEY (idTag) REFERENCES Tag(idTag) 
ON DELETE CASCADE
ON UPDATE CASCADE;

LOAD DATA LOCAL INFILE '/home/coralie/luna/Film/aPrTag.csv'
INTO TABLE aPrTag
FIELDS TERMINATED BY ';' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(idFilm,idTag);
